awk '
/const handleCreateSheet/ {
  print "  const handleOpenAssignModal = async () => {"
  print "    if (!activeSheetId) return;"
  print "    setIsAssigningTeam(true);"
  print "    try {"
  print "      const [usersData, membersData] = await Promise.all(["
  print "        dbService.list(\"users\"),"
  print "        dbService.list(\"sheet_members\")"
  print "      ]);"
  print "      setAllUsers(usersData as User[]);"
  print "      const currentMembers = membersData"
  print "        .filter((m: any) => m.sheet_id === activeSheetId)"
  print "        .map((m: any) => m.user_id);"
  print "      setSheetMembers(currentMembers);"
  print "    } catch (e) {"
  print "      console.error(\"Failed to load users for assignment\", e);"
  print "    }"
  print "  };"
  print ""
  print "  const handleSaveMembers = async () => {"
  print "    if (!activeSheetId) return;"
  print "    setIsUpdatingMembers(true);"
  print "    try {"
  print "      const existingMembers = await dbService.list(\"sheet_members\");"
  print "      const activeMembers = existingMembers.filter((m: any) => m.sheet_id === activeSheetId);"
  print "      "
  print "      // Simple implementation: delete all, then recreate"
  print "      for (const m of activeMembers) {"
  print "        if (m.id) await dbService.delete(\"sheet_members\", m.id);"
  print "      }"
  print "      "
  print "      for (const uid of sheetMembers) {"
  print "        await dbService.create(\"sheet_members\", {"
  print "          sheet_id: activeSheetId,"
  print "          user_id: uid,"
  print "          created_at: new Date().toISOString()"
  print "        });"
  print "      }"
  print "      setIsAssigningTeam(false);"
  print "      showToast(\"Team assigned successfully!\");"
  print "    } catch (e: any) {"
  print "      console.error(e);"
  print "      showToast(e.message || \"Failed to update team members\");"
  print "    } finally {"
  print "      setIsUpdatingMembers(false);"
  print "    }"
  print "  };"
  print ""
  print $0
  next
}
{ print }
' src/components/CRMLeadPipeline.tsx > tmp.tsx && mv tmp.tsx src/components/CRMLeadPipeline.tsx
